window.onload=L;
function L(){function a(a){return.5<=a-parseInt(a,10)?parseInt(a,10)+1:parseInt(a,10)}function w(c,B,d,z,x,r){var C=G.getContext("2d"),b=D.getContext("2d").getImageData(0,0,e,e),E;C.clearRect(0,0,e,e);document.onkeydown=function(a){39===a.keyCode?w(c,B,d,z,x+=5,r):37===a.keyCode?w(c,B,d,z,x-=5,r):38===a.keyCode?w(c,B,d,z,x,r-=5):40===a.keyCode?w(c,B,d,z,x,r+=5):107===a.keyCode?w(c,B,d,z-=5,x,r):109===a.keyCode&&w(c,B,d,z+=5,x,r)};var t=0,u,h,f,g,p,F,k,l,m,v,n;h=1/e;n=parseInt(e/2*Math.tan(.5),10);
for(u=B-.5;t<e;t+=y,u+=h)for(F=x,k=r,f=Math.cos(u),g=Math.sin(u),l=p=Math.cos(u-B),m=e;0<=F&&F<e&&0<=k&&k<e+200;){v=(n/l*z*q[a(F)][a(k)]+d)/q[a(F)][a(k)];if(v<m){E=4*(a(F)+a(k)*e);C.fillStyle="rgb("+b.data[E+0]+","+b.data[E+1]+","+b.data[E+2]+")";C.fillRect(t,v,y,m-v);if(0>v)break;m=v+.5}F+=f;k+=g;l+=p}}function b(a,c,z,d,e,r,F,k){function C(a,c,f,g){var h=c.d,d=c.c;c=c.b;return{d:h+~~((a.d-h)/f)*g,c:d+~~((a.c-d)/f)*g,b:c+~~((a.b-c)/f)*g}}for(var t=document.getElementById("canvas"),u=t.getContext("2d"),
h=0,f=0,g=0,p=0,b=0,g=0,v=u.createImageData(t.height,t.width),l=v.data,m={d:39,c:50,b:63},w={d:10,c:20,b:40},n={d:98,c:105,b:83},D={d:189,c:189,b:144},G={d:67,c:100,b:18},A={d:22,c:38,b:3},N={d:67,c:80,b:18},H={d:60,c:56,b:31},I={d:130,c:130,b:130},J={d:90,c:90,b:90},h=0;h<=a;h+=y)for(f=0;f<=a;f+=y){g={d:0,c:0,b:0};switch(z){case 1:p=c[h][f];0<=p&&p<=d?g=C(m,w,30,parseInt(100*p,10)):p>d&&p<=e?g=C(n,D,5,parseInt(100*p,10)-30):p>e&&p<=r?g=C(G,A,45,parseInt(100*p,10)-35):p>r&&p<=F?g=C(H,N,15,parseInt(100*
p,10)-80):p>F&&1>=k&&(g=C(I,J,5,parseInt(100*p,10)-98));break;case 2:g=Math.floor(250*q[h][f]);g={d:g,c:g,b:g};break;case 3:g=25*Math.round(~~(100*c[h][f])/25);g={d:g,c:g,b:g};break;case 4:.5>=c[h][f]?c[h][f]=0:.5<c[h][f]&&(c[h][f]=220);g=c[h][f];g={d:g,c:g,b:g};break;case 5:g=.5>c[h][f]?500*c[h][f]:500*(1-c[h][f]),p=.3<=c[h][f]&&.8>c[h][f]?500*(c[h][f]-.3):.3>c[h][f]?500*(.3-c[h][f]):500*(1.3-c[h][f]),b=.5<=c[h][f]?500*(c[h][f]-.5):500*(.5-c[h][f]),g={d:~~g,c:~~p,b:~~b}}for(p=0;p<=y;p++)for(b=0;b<=
y;b++){var M=4*(~~(h+p)+~~(f+b)*t.width);l[M]=g.d;l[M+1]=g.c;l[M+2]=g.b;l[M+3]=255}}u.putImageData(v,0,0)}var e,y,v,J,d,c,z=300,F=300,C,q,k=document.getElementById("generate"),l=document.getElementById("random"),N=document.getElementById("savemap"),D=document.getElementById("canvas"),H=D.getContext("2d"),G=document.getElementById("voxelview"),I=document.getElementById("seed");l.onclick=function(){I.value=Math.round(1E4*Math.random());location.search="?seed="+I.value;k.onclick()};k.onclick=function(){var k=
document.getElementById("terdim"),l=document.getElementById("roughness"),m=document.getElementById("unitsize"),n=document.getElementById("maptype"),x=document.getElementById("perspective"),r=document.getElementById("shadowmap"),A=document.getElementById("sunx"),O=document.getElementById("suny"),E=document.getElementById("waterLimit"),t=document.getElementById("sandLimit"),u=document.getElementById("grassLimit"),h=document.getElementById("mntLimit"),f=document.getElementById("rockLimit");J=parseInt(I.value,
10);v=parseInt(l.value,10);e=parseInt(k.value,10);y=parseInt(m.value,10);C=parseInt(n.options[n.selectedIndex].value,10);d=x.checked;c=r.checked;k=parseInt(E.value,10);t=parseInt(t.value,10);u=parseInt(u.value,10);h=parseInt(h.value,10);f=parseInt(f.value,10);v=v||8;e=e||256;y=y||1;k=(k?k:30)/100;t=(t?t:35)/100;u=(u?u:85)/100;h=(h?h:95)/100;f=(f?f:100)/100;c&&(z=parseInt(A.value,10),F=parseInt(O.value,10),isNaN(z)&&(z=300),isNaN(F)&&(F=300));D.width=e;D.height=e;q=P(e,y,v,J);b(e,q,C,k,t,u,h,f);if(c){var A=
z,O=F,f=document.createElement("canvas"),h=f.getContext("2d"),r=x=n=m=t=u=0,g;f.width=f.height=e;k=h.createImageData(f.width,f.height);l=k.data;for(u=0;u<e;u+=y)for(t=0;t<e;t+=y)for(m=A-u,n=O-t,x=4-q[u][t],r=Math.sqrt(m*m+n*n+x*x),m/=r,n/=r,x/=r,r=u,E=t,g=q[u][t];0<r&&r<e&&0<E&&E<e&&4>g;){if(q[a(r)][a(E)]>g){x=n=m=0;r=180;for(E=0;E<y;E++)for(g=0;g<y;g++){var p=4*(~~(u+E)+~~(t+g)*canvas.width);l[p]=m;l[p+1]=n;l[p+2]=x;l[p+3]+=r}break}r+=m*y;E+=n*y;g+=x*y}h.putImageData(k,0,0);H.drawImage(f,0,0)}d&&
(G.width=e,G.height=e,w(e,300,e/8,300,e/2,e+50));N.style.display="block"};N.onclick=function(){var a=D.toDataURL();window.open(a)};for(var n=location.search,n=n.split("&"),m=n.length;0<m;--m){var A=n[m-1].split("=");A[0]=A[0].replace("?","");n[m-1]=A}A=!0;for(m=n.length;0<m;--m)if("seed"===n[m-1][0]){I.value=n[m-1][1];A=!1;break}if(A)l.onclick();else k.onclick()};var R=new Q(123);
function P(a,w,b,e){function y(c){c/=2;var z=c/2;if(c>w){for(var e=z;e<a;e+=c)for(var C=z;C<a;C+=c){var q=e,k=C,l=c/2,b=q-l,D=k-l,H=q+l,G=k+l,I=d[b][D],n=d[H][D],m=d[b][G],A=d[H][G],K=4*l;d[q][k]=J((I+n+m+A)/4+v(K));var B=d[q][k];0<D&&(d[q][D]=0<D-l?(I+n+B+d[q][D-l])/4+v(K):(I+n+B)/3+v(K),d[q][D]=J(d[q][D]));G<a-0&&(d[q][G]=G+l<a?(m+A+B+d[q][G+l])/4+v(K):(m+A+B)/3+v(K),d[q][G]=J(d[q][G]));H<a-0&&(d[H][k]=H+l<a?(n+A+B+d[H+l][k])/4+v(K):(n+A+B)/3+v(K),d[H][k]=J(d[H][k]));0<b&&(d[b][k]=0<b-l?(I+m+B+
d[b-l][k])/4+v(K):(I+m+B)/3+v(K),d[b][k]=J(d[b][k]))}y(c)}}function v(c){c=c/(a+a)*b;return(R.random()-.5)*c}function J(a){1<a?a=1:0>a&&(a=0);return a}R=new Q(e);var d=function(a,d){for(var e=Array(a),b=0,q=0,b=0;b<a;++b)e[b]=Array(d);for(b=0;b<a;++b)for(q=0;q<d;++q)e[b][q]=0;return e}(a+1,a+1);(function(a,b){var d,e,q;a[0][0]=R.random();e=a[0][0];a[0][b]=R.random();q=a[0][b];a[b][0]=R.random();d=a[b][0];a[b][b]=R.random();a[b/2][b/2]=(e+q+d+a[b][b])/4;a[b/2][b/2]=J(a[b/2][b/2]);y(b)})(d,a);return d}
;function Q(a){void 0==a&&(a=(new Date).getTime());this.f=624;this.g=397;this.j=2567483615;this.i=2147483648;this.h=2147483647;this.a=Array(this.f);this.e=this.f+1;S(this,a)}function S(a,w){a.a[0]=w>>>0;for(a.e=1;a.e<a.f;a.e++)w=a.a[a.e-1]^a.a[a.e-1]>>>30,a.a[a.e]=(1812433253*((w&4294901760)>>>16)<<16)+1812433253*(w&65535)+a.e,a.a[a.e]>>>=0}
Q.prototype.random=function(){var a,w=[0,this.j];if(this.e>=this.f){var b;this.e==this.f+1&&S(this,5489);for(b=0;b<this.f-this.g;b++)a=this.a[b]&this.i|this.a[b+1]&this.h,this.a[b]=this.a[b+this.g]^a>>>1^w[a&1];for(;b<this.f-1;b++)a=this.a[b]&this.i|this.a[b+1]&this.h,this.a[b]=this.a[b+(this.g-this.f)]^a>>>1^w[a&1];a=this.a[this.f-1]&this.i|this.a[0]&this.h;this.a[this.f-1]=this.a[this.g-1]^a>>>1^w[a&1];this.e=0}a=this.a[this.e++];a^=a>>>11;a^=a<<7&2636928640;a^=a<<15&4022730752;return 1/4294967296*
((a^a>>>18)>>>0)};